return {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Info = ' ',
    Question = ' ',
    Hint = ' ',
  },
  documents = {
    File = ' ',
    Files = ' ',
    Folder = ' ',
    OpenFolder = ' ',
  },
  git = {
    Add = ' ',
    Mod = ' ',
    Remove = ' ',
    Ignore = ' ',
    Rename = ' ',
    Diff = ' ',
    Repo = ' ',
  },
  kinds = {
    File = ' ',
    Module = ' ',
    Namespace = ' ',
    Package = ' ',
    Class = ' ',
    Method = ' ',
    Property = ' ',
    Field = '󰉺 ',
    Constructor = ' ',
    Enum = ' ',
    Interface = ' ',
    Function = '󰊕 ',
    Variable = ' ',
    Constant = ' ',
    String = ' ',
    Number = ' ',
    Boolean = ' ',
    Array = ' ',
    Object = ' ',
    Key = ' ',
    Null = '󰟢 ',
    EnumMember = ' ',
    Struct = ' ',
    Event = ' ',
    Operator = ' ',
    TypeParameter = ' ',
  },
  ui = {
    Bug = ' ',
    Check = ' ',
    ChevronRight = '',
    Fire = ' ',
    History = ' ',
    Lightbulb = ' ',
    Project = ' ',
    Search = ' ',
    Telescope = ' ',
  },
}
